// DO NOT EDIT, generated by goctl
package handler

import (
	"jwttoken/internal/utils"
	"net/http"
	"strings"

	"github.com/tal-tech/go-zero/rest/httpx"
)

//鉴权白名单
var whiteList []string = []string{
	"/open/",
}

func Auth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Add("X-Middleware", "auth")

		uri := r.RequestURI
		isInWhiteList := false
		for _, v := range whiteList {
			if strings.Contains(uri, v) {
				isInWhiteList = true
			}
		}
		if isInWhiteList {
			next(w, r)
			return
		}

		token := r.Header.Get("X-Token")
		_, err := utils.DecodeJwtToken(token)
		if err != nil {
			httpx.Error(w, err)
			return
		}
		//没报错就继续
		next(w, r)
	}
}
