// DO NOT EDIT, generated by goctl
package types

type UserOptReq struct {
	Mobile string `form:"mobile"`
	Passwd string `form:"passwd"`
	Code   string `form:"code,optional"`
}

type UserOptResp struct {
	Id    uint   `json:"id"`
	Token string `json:"token"`
}

type UserUpdateReq struct {
	Id     uint   `form:"id"`
	Mobile string `form:"mobile,optional"`
}
