// DO NOT EDIT, generated by goctl
package handler

import (
	"net/http"

	open "file/internal/handler/open"
	"file/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes([]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/open/authorization",
			Handler: open.AuthorizationHandler(serverCtx),
		},
	})
	RegisterFileHandlers(engine, serverCtx)
}
